AWSTemplateFormatVersion: 2010-09-09
Description: ' S3 bucket training'
Metadata:
  SupportedResources: 'S3'
Parameters:
  BucketNameParam:
    Type: String
    Description: 'Friendly name parameter for the s3 bucket created by this template'
    Default: 'stelligent-u-michael.mcelreath.labs'
Resources:
  SimpleBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['-', [!Ref AWS::Region, !Ref AWS::AccountId, !Ref BucketNameParam]]    
  PublicReadBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref SimpleBucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref SimpleBucket
                - /*
            Principal: '*'