AWSTemplateFormatVersion: 2010-09-09
Description: 'S3 bucket training'
Metadata:
  SupportedResources: 'S3'
Parameters:
  BucketNameParam:
    Type: String
    Description: 'Name parameter for the s3 bucket'
    Default: 'stelligent-u-michael.mcelreath.labs'
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['-', [!Ref AWS::Region, !Ref AWS::AccountId, !Ref BucketNameParam]]    
  ReadBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref Bucket
                - /*
            Principal: '*'