---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  A template for creating a S3 bucket. 


Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 Bucket to create

# Conditions:
#   CreateS3Bucket: Equals
#     - !Ref AWS::Region
#     - us-east-1

Resources:
   S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ "-", [ !Ref AWS::AccountId, !Ref BucketName ] ]
    