---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  A template for creating a S3 bucket. 

Resources:
   S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "Mike-Uni-Training"
    