AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates resource necessary for 4-1-*' 
Metadata:
  SupportedResources: 'EC2'
Parameters:
  VpcName:
    Description: 'Name of VPC'
    Type: String
    Default: 'mike-training-peer'
  VpcCIDR:
    Description: 'CIDR VPC'
    Type: String
    Default: 172.31.0.0/16
  PrivateSubnet1CIDR:
    Description: 'CIDR Range of the Private subnets'
    Type: String
    Default: 172.31.30.0/24

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: false
      EnableDnsHostnames: false
      Tags:
      - Key: 'Name'
        Value: !Ref VpcName
      - Key: 'user'
        Value: 'michael.mcelreath.labs'
      - Key: 'stelligent-u-lab'
        Value: '4.1'


  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: !Ref PrivateSubnet1CIDR
      Tags:
      - Key: 'user'
        Value: 'michael.mcelreath.labs'
      - Key: 'stelligent-u-lab'
        Value: '4.1'

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: 'user'
        Value: 'michael.mcelreath.labs'
      - Key: 'stelligent-u-lab'
        Value: '4.1'

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: VPC
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet1


  NACL:
    Type: AWS::EC2::NetworkAcl
    DependsOn: VPC
    Properties: 
      VpcId: !Ref VPC

  InboundRule2:
    Type: AWS::EC2::NetworkAclEntry
    DependsOn: NACL
    Properties:
       NetworkAclId:
         Ref: NACL
       RuleNumber: 200
       Protocol: 6
       RuleAction: allow
       CidrBlock: 10.192.0.0/16
       PortRange:
         From: 1024
         To: 65535
  InboundRule3:
    Type: AWS::EC2::NetworkAclEntry
    DependsOn: NACL
    Properties:
      NetworkAclId:
         Ref: NACL
      RuleNumber: 300
      Protocol: 1
      Icmp:
        Type: -1
        Code: -1
      RuleAction: allow
      CidrBlock: 10.192.0.0/16
  OutboundRule:
    Type: AWS::EC2::NetworkAclEntry
    DependsOn: NACL
    Properties:
       NetworkAclId:
         Ref: NACL
       RuleNumber: 100
       Protocol: 6
       Egress: true
       RuleAction: allow
       CidrBlock: 0.0.0.0/0
       PortRange:
         From: 0
         To: 65535
  OutboundRule2:
    Type: AWS::EC2::NetworkAclEntry
    DependsOn: NACL
    Properties:
       NetworkAclId:
         Ref: NACL
       RuleNumber: 200
       Protocol: 1
       Icmp:
        Type: -1
        Code: -1
       Egress: true
       RuleAction: allow
       CidrBlock: 0.0.0.0/0
  
  PrivateNACL:
    Type: AWS::EC2::NetworkAcl
    Properties: 
      VpcId: !Ref VPC

  PrivateInboundRule1:
    Type: AWS::EC2::NetworkAclEntry
    DependsOn: PrivateNACL
    Properties:
       NetworkAclId:
         Ref: PrivateNACL
       RuleNumber: 100
       Protocol: 6
       RuleAction: allow
       CidrBlock: 10.192.0.0/16
       PortRange:
         From: 22
         To: 22
  PrivateInboundRule2:
    Type: AWS::EC2::NetworkAclEntry
    DependsOn: PrivateNACL
    Properties:
       NetworkAclId:
         Ref: PrivateNACL
       RuleNumber: 200
       Protocol: 1
       Icmp:
        Type: -1
        Code: -1
       RuleAction: allow
       CidrBlock: 10.192.0.0/16
  PrivateInboundRule3:
    Type: AWS::EC2::NetworkAclEntry
    DependsOn: PrivateNACL
    Properties:
       NetworkAclId:
         Ref: PrivateNACL
       RuleNumber: 300
       Protocol: 6
       RuleAction: allow
       CidrBlock: 10.192.20.0/24
       PortRange:
         From: 80
         To: 80
    
  PrivateOutboundRule1:
    Type: AWS::EC2::NetworkAclEntry
    DependsOn: PrivateNACL
    Properties:
       NetworkAclId:
         Ref: PrivateNACL
       RuleNumber: 100
       Protocol: 6
       Egress: true
       RuleAction: allow
       CidrBlock: 10.192.20.0/24
       PortRange:
         From: 0
         To: 65535
  PrivateOutboundRule2:
    Type: AWS::EC2::NetworkAclEntry
    DependsOn: PrivateNACL
    Properties:
       NetworkAclId:
         Ref: PrivateNACL
       RuleNumber: 200
       Protocol: 1
       Icmp:
        Type: -1
        Code: -1
       Egress: true
       RuleAction: allow
       CidrBlock: 10.192.20.0/24
  
  PrivateSubnetNACLAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    DependsOn: PrivateNACL
    Properties: 
      NetworkAclId: !Ref PrivateNACL
      SubnetId: !Ref PrivateSubnet1

  # S3Endpoint:
  #   Type: AWS::EC2::VPCEndpoint
  #   Properties: 
  #     ServiceName: S3
  #     SubnetIds: 
  #       - subnet-05da660e07c45226e
  #     VpcId: vpc-0da5746e7ee65ce40