---
AWSTemplateFormatVersion: 2010-09-09

Description: 'S3 bucket for training'

Metadata:
  CreatedBy: 'mmcelreath'
  SupportedResources: 'S3'

Parameters:
  BucketNameParam:
    Type: String
    Description: 'Friendly name parameter'
    Default: 'mmcelreath-training'

Resources:
  SimpleBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['-', [!Ref AWS::Region, !Ref AWS::AccountId, !Ref BucketNameParam]]