AWSTemplateFormatVersion: 2010-09-09
Description: 'Minimal S3 bucket CFN template for stelligent-u'
Metadata:
  SupportedResources: 'S3'
Parameters:
  BucketNameParam:
    Type: String
    Description: 'S3 bucket training'
    Default: 'stelligent-u-michael.mcelreath.labs'
Resources:
  SimpleBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['-', [!Ref AWS::Region, !Ref AWS::AccountId, !Ref BucketNameParam]]
      BucketEncryption: 
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
             SSEAlgorithm: 'aws:kms'
             KMSMasterKeyID: 'arn:aws:kms:us-west-2:324320755747:key/6adc2c83-1b8f-47b4-802c-ef02fde3615c' 
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: NormalObjects
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
            NoncurrentVersionExpirationInDays: 7
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
  PublicReadBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref SimpleBucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref SimpleBucket
                - /*
            Principal: '*'